/**
 * This file defines names of metrics and events.
 */

/**
 * Names of metrics. This list is generated by ./scripts/types.js file.
 */
export type MetricsNames =
  | "base64Length"
  | "colors"
  | "comments"
  | "commentsLength"
  | "complexSelectors"
  | "declarations"
  | "duplicatedProperties"
  | "duplicatedSelectors"
  | "emptyRules"
  | "expressions"
  | "importants"
  | "imports"
  | "length"
  | "mediaQueries"
  | "multiClassesSelectors"
  | "notMinified"
  | "oldIEFixes"
  | "oldPropertyPrefixes"
  | "parsingErrors"
  | "propertyResets"
  | "qualifiedSelectors"
  | "redundantBodySelectors"
  | "redundantChildNodesSelectors"
  | "rules"
  | "selectorLengthAvg"
  | "selectors"
  | "selectorsByAttribute"
  | "selectorsByClass"
  | "selectorsById"
  | "selectorsByPseudo"
  | "selectorsByTag"
  | "specificityClassAvg"
  | "specificityClassTotal"
  | "specificityIdAvg"
  | "specificityIdTotal"
  | "specificityTagAvg"
  | "specificityTagTotal";

/**
 * Names of events. This list is generated by ./scripts/types.js file.
 */
export type EventsNames =
  | "comment" /* (comment) */
  | "css" /* (css) */
  | "declaration" /* (rule, property, value) */
  | "error" /* (err) */
  | "expression" /* (selector, expression) */
  | "font-face" /* (rule) */
  | "import" /* (url) */
  | "media" /* (query) */
  | "mediaEnd" /* (query) */
  | "report" /* () */
  | "rule" /* (rule) */
  | "selector" /* (rule, selector, expressions) */;

/**
 * Encapsulates a set of metrics
 */
export type Metrics = { [metric in MetricsNames]: number };

/**
 * Encapsulates a set of offenders
 */
export type Offenders = { [metric in MetricsNames]: Array<Object> };
