# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to npm and GitHub Packages

on:
  release:
    types: [created]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      #
      # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm
      #
      - uses: actions/setup-node@master
        with:
         node-version: '14.x'
         cache: 'npm'
         registry-url: 'https://npm.pkg.github.com'

      - run: npm ci

      - name: Publish to GitHub Packages
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


      - uses: actions/setup-node@master
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
